#!/usr/bin/env bash
# Script that transfers a file from the client to the server using scp
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to the variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH-TO-SSH-KEY=$4

#Transfer the file using scp with strict hosy key checking disabled
scp  -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@IP:~/"

exit 0