#!/usr/bin/env bash
# Installs nginx, starts the service, and configures it to return 'Hello World!' from root

# Update package lists
apt-get update -y

# Install nginx
apt-get install nginx -y

# Replace default HTML page with 'Hello World!'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Start nginx without using systemctl
service nginx start || /etc/init.d/nginx start
