#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

# Update package list
apt-get update -y

# Install Nginx
apt-get install -y nginx

# Get hostname
# shellcheck disable=SC2154
hostname=$(hostname)

# Configure Nginx with custom header
cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    add_header X-Served-By $hostname;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Test Nginx configuration
nginx -t

# Restart Nginx
service nginx restart
